import type { Task, UserProfile, Meeting, Message } from "./types";

// Mock current user
export const MOCK_USER: UserProfile = {
  id: "user-001",
  name: "Alex Chen",
  email: "alex.chen@example.com",
  role: "Product Manager",
  skills: ["Project Management", "Agile", "Stakeholder Communication", "Roadmapping"],
  capacity_hours: 40,
  assigned_hours: 28,
  avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
  resume_url: "https://example.com/resume.pdf",
  phone: "+1 555-0123",
  bio: "Experienced product manager focused on AI-driven solutions.",
  status: "active",
  availability: "Available Mon-Fri 9am-5pm PST",
};

// Mock team members
export const MOCK_EMPLOYEES: UserProfile[] = [
  MOCK_USER,
  {
    id: "user-002",
    name: "Jordan Rivera",
    email: "jordan.rivera@example.com",
    role: "Senior Developer",
    skills: ["React", "TypeScript", "Node.js", "Python", "System Design"],
    capacity_hours: 40,
    assigned_hours: 35,
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan",
    status: "busy",
  },
  {
    id: "user-003",
    name: "Sam Taylor",
    email: "sam.taylor@example.com",
    role: "UX Designer",
    skills: ["Figma", "User Research", "Prototyping", "Design Systems"],
    capacity_hours: 40,
    assigned_hours: 22,
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sam",
    status: "active",
  },
  {
    id: "user-004",
    name: "Morgan Lee",
    email: "morgan.lee@example.com",
    role: "DevOps Engineer",
    skills: ["Kubernetes", "GCP", "Docker", "CI/CD", "Terraform"],
    capacity_hours: 40,
    assigned_hours: 30,
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Morgan",
    status: "active",
  },
  {
    id: "user-005",
    name: "Casey Kim",
    email: "casey.kim@example.com",
    role: "QA Engineer",
    skills: ["Test Automation", "Selenium", "Performance Testing", "API Testing"],
    capacity_hours: 40,
    assigned_hours: 18,
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Casey",
    status: "on_leave",
  },
];

// Mock tasks
export const MOCK_TASKS: Task[] = [
  {
    id: "task-001",
    title: "Implement user authentication flow",
    description: "Build complete OAuth2 authentication with Google sign-in, token refresh, and session management.",
    tags: ["authentication", "security", "backend"],
    attachments: [],
    complexity: "high",
    priority: 1,
    deadline: "2025-11-30",
    status: "in_progress",
    predicted_hours: 16,
    assigned_to: "user-002",
    created_by: "user-001",
    watchers: ["user-001", "user-004"],
    activity_log: [
      { timestamp: "2025-11-20T09:00:00Z", actor: "user-001", action: "Created task" },
      { timestamp: "2025-11-21T10:30:00Z", actor: "user-002", action: "Started working on task" },
    ],
    created_at: "2025-11-20T09:00:00Z",
    ai_reason: "High priority due to blocking other features. Jordan has relevant experience.",
    customer_name: "Acme Corp",
    project_name: "Portal Redesign",
  },
  {
    id: "task-002",
    title: "Design dashboard wireframes",
    description: "Create high-fidelity wireframes for the main dashboard showing KPIs, recent activity, and quick actions.",
    tags: ["design", "ui/ux", "dashboard"],
    attachments: [],
    complexity: "medium",
    priority: 2,
    deadline: "2025-11-28",
    status: "in_review",
    predicted_hours: 8,
    assigned_to: "user-003",
    created_by: "user-001",
    watchers: ["user-001"],
    activity_log: [
      { timestamp: "2025-11-18T14:00:00Z", actor: "user-001", action: "Created task" },
      { timestamp: "2025-11-22T16:00:00Z", actor: "user-003", action: "Submitted for review" },
    ],
    created_at: "2025-11-18T14:00:00Z",
    ai_reason: "Design needed before frontend development can begin.",
    meeting_suggestion: {
      attendees: ["user-001", "user-003"],
      duration: 30,
      day: "2025-11-26",
    },
    customer_name: "TechStart Inc",
    project_name: "Analytics Platform",
  },
  {
    id: "task-003",
    title: "Set up CI/CD pipeline",
    description: "Configure GitHub Actions for automated testing, building, and deployment to GCP Cloud Run.",
    tags: ["devops", "infrastructure", "automation"],
    attachments: [],
    complexity: "medium",
    priority: 3,
    deadline: "2025-12-05",
    status: "open",
    predicted_hours: 12,
    assigned_to: "user-004",
    created_by: "user-001",
    watchers: ["user-001", "user-002"],
    activity_log: [
      { timestamp: "2025-11-19T11:00:00Z", actor: "user-001", action: "Created task" },
    ],
    created_at: "2025-11-19T11:00:00Z",
    ai_reason: "Essential for streamlined deployments. Morgan specializes in this.",
    customer_name: "Global Solutions",
    project_name: "Infrastructure Upgrade",
  },
  {
    id: "task-004",
    title: "Write API documentation",
    description: "Document all REST API endpoints with OpenAPI/Swagger spec, including request/response examples.",
    tags: ["documentation", "api", "backend"],
    attachments: [],
    complexity: "low",
    priority: 4,
    deadline: "2025-12-10",
    status: "open",
    predicted_hours: 6,
    assigned_to: undefined,
    created_by: "user-001",
    watchers: ["user-001"],
    activity_log: [
      { timestamp: "2025-11-22T09:00:00Z", actor: "user-001", action: "Created task" },
    ],
    created_at: "2025-11-22T09:00:00Z",
    ai_reason: "Will help onboard new developers. Low complexity but important.",
    customer_name: "Internal",
    project_name: "Developer Experience",
  },
  {
    id: "task-005",
    title: "Performance optimization for task list",
    description: "Implement virtualization and optimize queries to handle 10k+ tasks without lag.",
    tags: ["performance", "frontend", "optimization"],
    attachments: [],
    complexity: "high",
    priority: 2,
    deadline: "2025-12-01",
    status: "blocked",
    predicted_hours: 20,
    assigned_to: "user-002",
    created_by: "user-001",
    watchers: ["user-001", "user-003"],
    activity_log: [
      { timestamp: "2025-11-17T13:00:00Z", actor: "user-001", action: "Created task" },
      { timestamp: "2025-11-23T10:00:00Z", actor: "user-002", action: "Blocked - waiting for design specs" },
    ],
    created_at: "2025-11-17T13:00:00Z",
    ai_reason: "Blocked by task-002. High complexity requires senior developer.",
    customer_name: "Acme Corp",
    project_name: "Portal Redesign",
  },
  {
    id: "task-006",
    title: "User onboarding tutorial",
    description: "Create interactive onboarding flow for new users with tooltips and guided tour.",
    tags: ["ux", "onboarding", "frontend"],
    attachments: [],
    complexity: "medium",
    priority: 5,
    deadline: "2025-12-15",
    status: "completed",
    predicted_hours: 10,
    assigned_to: "user-003",
    created_by: "user-001",
    watchers: ["user-001"],
    activity_log: [
      { timestamp: "2025-11-10T09:00:00Z", actor: "user-001", action: "Created task" },
      { timestamp: "2025-11-20T17:00:00Z", actor: "user-003", action: "Completed task" },
    ],
    created_at: "2025-11-10T09:00:00Z",
    customer_name: "TechStart Inc",
    project_name: "Analytics Platform",
  },
  {
    id: "task-007",
    title: "Integrate Gemini AI for task suggestions",
    description: "Connect to Gemini API to provide AI-powered task assignment suggestions and time estimates.",
    tags: ["ai", "integration", "backend"],
    attachments: [],
    complexity: "high",
    priority: 1,
    deadline: "2025-11-27",
    status: "in_progress",
    predicted_hours: 24,
    assigned_to: "user-002",
    created_by: "user-001",
    watchers: ["user-001", "user-004"],
    activity_log: [
      { timestamp: "2025-11-15T10:00:00Z", actor: "user-001", action: "Created task" },
      { timestamp: "2025-11-22T09:00:00Z", actor: "user-002", action: "API integration started" },
    ],
    created_at: "2025-11-15T10:00:00Z",
    ai_reason: "Core differentiating feature. Highest priority.",
    customer_name: "Internal",
    project_name: "AI Features",
  },
];

// Mock meetings
export const MOCK_MEETINGS: Meeting[] = [
  {
    id: "meeting-001",
    title: "Sprint Planning",
    description: "Plan tasks for the upcoming sprint and review backlog priorities.",
    attendees: ["user-001", "user-002", "user-003", "user-004"],
    date: "2025-11-25T10:00:00Z",
    duration_minutes: 60,
    created_by: "user-001",
    meet_url: "https://meet.google.com/abc-defg-hij",
  },
  {
    id: "meeting-002",
    title: "Design Review: Dashboard",
    description: "Review Sam's dashboard wireframes and provide feedback.",
    attendees: ["user-001", "user-003"],
    date: "2025-11-26T14:00:00Z",
    duration_minutes: 30,
    task_id: "task-002",
    created_by: "user-001",
    meet_url: "https://meet.google.com/klm-nopq-rst",
  },
  {
    id: "meeting-003",
    title: "1:1 with Jordan",
    description: "Weekly sync on authentication and AI integration progress.",
    attendees: ["user-001", "user-002"],
    date: "2025-11-27T11:00:00Z",
    duration_minutes: 30,
    created_by: "user-001",
    meet_url: "https://meet.google.com/uvw-xyz-123",
  },
  {
    id: "meeting-004",
    title: "Team Standup",
    description: "Daily standup - what did you do, what will you do, any blockers?",
    attendees: ["user-001", "user-002", "user-003", "user-004", "user-005"],
    date: "2025-11-25T09:00:00Z",
    duration_minutes: 15,
    created_by: "user-001",
  },
];

// Mock messages for task chat
export const MOCK_MESSAGES: Record<string, Message[]> = {
  "task-001": [
    {
      id: "msg-001",
      task_id: "task-001",
      sender_id: "user-002",
      text: "Started working on the OAuth flow. Using Firebase Auth as the base.",
      attachments: [],
      created_at: "2025-11-21T10:30:00Z",
    },
    {
      id: "msg-002",
      task_id: "task-001",
      sender_id: "user-001",
      text: "Great! Make sure to handle token refresh gracefully. We need 24h sessions.",
      attachments: [],
      created_at: "2025-11-21T11:15:00Z",
    },
    {
      id: "msg-003",
      task_id: "task-001",
      sender_id: "user-002",
      text: "Got it. I'll implement silent refresh. Should be done by end of week.",
      attachments: [],
      created_at: "2025-11-21T11:20:00Z",
    },
  ],
  "task-002": [
    {
      id: "msg-004",
      task_id: "task-002",
      sender_id: "user-003",
      text: "Uploaded initial wireframes to Figma. Link in the attachments.",
      attachments: [],
      created_at: "2025-11-22T15:00:00Z",
    },
    {
      id: "msg-005",
      task_id: "task-002",
      sender_id: "user-001",
      text: "Looks good! Can we add a quick-actions panel on the right side?",
      attachments: [],
      created_at: "2025-11-22T16:30:00Z",
    },
  ],
};

// Enable mock mode - set to true to use mock data
export const USE_MOCK_DATA = true;

